-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=1,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={16781313,'Snipper',77},
    [2]={16781314,'Snipper',77},
    [3]={16781315,'Big Jaw',197},
    [4]={16781316,'Fishtrap',114},
    [5]={16781317,'Protozoan',229},
    [6]={16781318,'Aipaloovik',197},
    [7]={16781319,'Thickshell',77},
    [8]={16781320,'Giant Pugil',197},
    [9]={16781321,'Flytrap',114},
    [10]={16781322,'Flytrap',114},
    [11]={16781323,'Ooze',229},
    [12]={16781324,'Thunder Elemental',105},
    [13]={16781325,'Water Elemental',106},
    [16]={16781328,'Orc\'s Wyvern',193},
  },
}
