-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=148,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17383425,'Ancient Quadav',202},
    [2]={17383426,'Darksteel Quadav',202},
    [3]={17383427,'Platinum Quadav',202},
    [4]={17383428,'Sapphire Quadav',202},
    [5]={17383429,'Ancient Quadav',202},
    [6]={17383430,'Darksteel Quadav',202},
    [7]={17383431,'Platinum Quadav',202},
    [8]={17383432,'Sapphire Quadav',202},
    [10]={17383434,'Darksteel Quadav',202},
    [11]={17383435,'Sapphire Quadav',202},
    [12]={17383436,'Darksteel Quadav',202},
    [13]={17383437,'Sapphire Quadav',202},
    [14]={17383438,'Ancient Quadav',202},
    [15]={17383439,'Platinum Quadav',202},
    [22]={17383446,'Hu\'Rhe Marrowgorger',202},
  },
}
