-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=154,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17408001,'Demonic Pugil',197},
    [2]={17408002,'Demonic Pugil',197},
    [3]={17408003,'Demonic Pugil',197},
    [4]={17408004,'Demonic Pugil',197},
    [5]={17408005,'Demonic Pugil',197},
    [6]={17408006,'Bark Tarantula',235},
    [7]={17408007,'Bark Tarantula',235},
    [8]={17408008,'Bark Tarantula',235},
    [14]={17408014,'Demonic Rose',186},
    [15]={17408015,'Bark Tarantula',235},
    [16]={17408016,'Bark Tarantula',235},
    [17]={17408017,'Bark Tarantula',235},
    [26]={17408026,'Bark Tarantula',235},
    [27]={17408027,'Bark Tarantula',235},
    [28]={17408028,'Bark Tarantula',235},
    [29]={17408029,'Bark Tarantula',235},
    [30]={17408030,'Bark Tarantula',235},
    [31]={17408031,'Bark Tarantula',235},
  },
}
