-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=156,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [22]={17416214,'Klara',482},
    [24]={17416216,'Zeid',480},
    [25]={17416217,'Klara',482},
    [27]={17416219,'Zeid',480},
    [28]={17416220,'Klara',482},
    [30]={17416222,'Zeid',480},
  },
}
