-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=168,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [17]={17465361,'Maat\'s Wyvern',193},
    [19]={17465363,'Maat\'s Wyvern',193},
    [21]={17465365,'Maat\'s Wyvern',193},
    [70]={17465414,'Nanaa Mihgo',151},
    [71]={17465415,'Cha Lebagta',151},
    [72]={17465416,'Bopa Greso',151},
    [73]={17465417,'Goblin Repossessor',133},
    [74]={17465418,'Goblin Intimidator',133},
    [75]={17465419,'Goblin Enforcer',133},
  },
}
