-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=17,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [5]={16846853,'Weeper',256},
    [6]={16846854,'Weeper',256},
    [7]={16846855,'Weeper',256},
    [10]={16846858,'Weeper',256},
    [11]={16846859,'Weeper',256},
    [12]={16846860,'Weeper',256},
    [15]={16846863,'Weeper',256},
    [16]={16846864,'Weeper',256},
    [17]={16846865,'Weeper',256},
  },
}
