-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=186,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [5]={17539077,'Vanguard\'s Scorpion',217},
    [17]={17539089,'Vanguard\'s Wyvern',193},
    [27]={17539099,'Vanguard\'s Avatar',34},
    [34]={17539106,'Vanguard\'s Wyvern',193},
    [39]={17539111,'Vanguard\'s Scorpion',217},
    [41]={17539113,'Vanguard\'s Wyvern',193},
    [72]={17539144,'Vanguard\'s Avatar',34},
    [93]={17539165,'Vanguard\'s Wyvern',193},
    [95]={17539167,'Vanguard\'s Avatar',34},
    [106]={17539178,'Vanguard\'s Scorpion',217},
    [126]={17539198,'Vanguard\'s Scorpion',217},
    [128]={17539200,'Vanguard\'s Wyvern',193},
    [138]={17539210,'Vanguard\'s Avatar',34},
    [140]={17539212,'Vanguard\'s Avatar',34},
    [142]={17539214,'Vanguard\'s Scorpion',217},
    [151]={17539223,'Vanguard\'s Avatar',34},
    [166]={17539238,'Vanguard\'s Scorpion',217},
    [168]={17539240,'Vanguard\'s Wyvern',193},
    [176]={17539248,'Vanguard\'s Scorpion',217},
    [178]={17539250,'Vanguard\'s Wyvern',193},
    [201]={17539273,'Vanguard\'s Avatar',34},
    [213]={17539285,'Vanguard\'s Scorpion',217},
    [220]={17539292,'Vanguard\'s Wyvern',193},
    [237]={17539309,'Ra\'Gho\'s Avatar',323},
    [240]={17539312,'Arch Gu\'Dha Effigy',94},
  },
}
