-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=209,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [28]={17633308,'Titan Prime',321},
    [29]={17633309,'Titan Prime',321},
    [30]={17633310,'Titan Prime',321},
    [31]={17633311,'Titan Prime',321},
    [32]={17633312,'Titan Prime',321},
    [33]={17633313,'Titan Prime',321},
    [34]={17633314,'Titan Prime',321},
    [35]={17633315,'Titan Prime',321},
    [36]={17633316,'Titan Prime',321},
    [37]={17633317,'Titan Prime',321},
    [38]={17633318,'Titan Prime',321},
    [39]={17633319,'Titan Prime',321},
    [40]={17633320,'Titan Prime',321},
    [41]={17633321,'Titan Prime',321},
    [42]={17633322,'Titan Prime',321},
  },
}
