-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=220,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17678337,'Sea Pugil',197},
    [2]={17678338,'Ocean Crab',77},
    [3]={17678339,'Ocean Pugil',197},
    [4]={17678340,'Pirate Pugil',197},
    [6]={17678342,'Sea Crab',77},
    [7]={17678343,'Sea Crab',77},
    [8]={17678344,'Sea Pugil',197},
    [9]={17678345,'Sea Pugil',197},
    [11]={17678347,'Phantom',121},
    [12]={17678348,'Thunder Elemental',105},
    [13]={17678349,'Water Elemental',106},
  },
}
