-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=221,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17682433,'Sea Pugil',197},
    [2]={17682434,'Ocean Crab',77},
    [3]={17682435,'Ocean Pugil',197},
    [4]={17682436,'Pirate Pugil',197},
    [6]={17682438,'Sea Crab',77},
    [7]={17682439,'Sea Crab',77},
    [8]={17682440,'Sea Pugil',197},
    [9]={17682441,'Sea Pugil',197},
    [11]={17682443,'Phantom',121},
    [12]={17682444,'Thunder Elemental',105},
    [13]={17682445,'Water Elemental',106},
  },
}
