-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=222,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17686529,'Provenance Watcher',462},
    [2]={17686530,'Crystal Fetter',237},
    [3]={17686531,'Crystal Fetter',237},
    [4]={17686532,'Crystal Fetter',237},
    [6]={17686534,'Crystal Fetter',237},
    [7]={17686535,'Crystal Fetter',237},
    [8]={17686536,'Crystal Fetter',237},
    [10]={17686538,'Crystal Fetter',237},
    [11]={17686539,'Crystal Fetter',237},
    [12]={17686540,'Crystal Fetter',237},
    [13]={17686541,'Sarbaz',450},
    [14]={17686542,'Pil',450},
    [15]={17686543,'Asb',450},
    [16]={17686544,'Rukh',450},
    [17]={17686545,'Shah',450},
    [18]={17686546,'Wazir',450},
    [23]={17686551,'Shah',450},
    [24]={17686552,'Wazir',450},
  },
}
