-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=227,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17707009,'Sea Pugil',197},
    [2]={17707010,'Ocean Crab',77},
    [3]={17707011,'Ocean Pugil',197},
    [4]={17707012,'Pirate Pugil',197},
    [5]={17707013,'Sea Monk',218},
    [6]={17707014,'Sea Crab',77},
    [7]={17707015,'Sea Crab',77},
    [8]={17707016,'Sea Pugil',197},
    [9]={17707017,'Sea Pugil',197},
    [10]={17707018,'Sea Monk',218},
    [11]={17707019,'Phantom',121},
  },
}
