-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=228,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17711105,'Sea Pugil',197},
    [2]={17711106,'Ocean Crab',77},
    [3]={17711107,'Ocean Pugil',197},
    [4]={17711108,'Pirate Pugil',197},
    [5]={17711109,'Sea Monk',218},
    [6]={17711110,'Sea Crab',77},
    [7]={17711111,'Sea Crab',77},
    [8]={17711112,'Sea Pugil',197},
    [9]={17711113,'Sea Pugil',197},
    [10]={17711114,'Sea Monk',218},
    [11]={17711115,'Phantom',121},
  },
}
