-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=259,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [63]={17838143,'Zurko-Bazurko',153},
    [69]={17838149,'The Briars',149},
    [70]={17838150,'The Briars',149},
    [205]={17838285,'Balamor',492},
    [207]={17838287,'Balamor\'s Sycophant',447},
    [208]={17838288,'Regicidal Dullahan',447},
    [209]={17838289,'Balamor\'s Sycophant',447},
  },
}
