-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=3,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={16789505,'Ghost Crab',77},
    [2]={16789506,'Ghost Crab',77},
    [3]={16789507,'Greater Pugil',197},
    [4]={16789508,'Kraken',218},
    [7]={16789511,'Cutter',77},
    [8]={16789512,'Fatty Pugil',197},
    [9]={16789513,'Uragnite',251},
    [10]={16789514,'Uragnite',251},
    [11]={16789515,'Clot',66},
    [12]={16789516,'Clot',66},
    [13]={16789517,'Colossal Calamari',218},
  },
}
