-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=33,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [23]={16912407,'Aern\'s Wynav',193},
    [24]={16912408,'Aern\'s Xzomit',269},
    [37]={16912421,'Aern\'s Elemental',100},
    [97]={16912481,'Aern\'s Wynav',193},
    [98]={16912482,'Aern\'s Elemental',100},
    [99]={16912483,'Aern\'s Xzomit',269},
    [136]={16912520,'Aern\'s Wynav',193},
    [146]={16912530,'Aern\'s Elemental',100},
    [147]={16912531,'Aern\'s Xzomit',269},
    [189]={16912573,'Aern\'s Wynav',193},
    [190]={16912574,'Aern\'s Wynav',193},
    [209]={16912593,'Aern\'s Elemental',100},
    [230]={16912614,'Aern\'s Xzomit',269},
    [283]={16912667,'Aern\'s Xzomit',269},
    [290]={16912674,'Aern\'s Wynav',193},
    [329]={16912713,'Aern\'s Elemental',100},
    [341]={16912725,'Aern\'s Xzomit',269},
    [343]={16912727,'Aern\'s Wynav',193},
    [364]={16912748,'Aern\'s Wynav',193},
    [379]={16912763,'Aern\'s Elemental',100},
    [493]={16912877,'Aern\'s Wynav',193},
    [494]={16912878,'Aern\'s Wynav',193},
    [495]={16912879,'Aern\'s Wynav',193},
    [496]={16912880,'Aern\'s Wynav',193},
    [497]={16912881,'Aern\'s Wynav',193},
    [498]={16912882,'Aern\'s Wynav',193},
  },
}
