-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=34,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [89]={16916569,'Aern\'s Elemental',100},
    [99]={16916579,'Aern\'s Wynav',193},
    [110]={16916590,'Aern\'s Euvhi',109},
    [119]={16916599,'Aern\'s Wynav',193},
    [138]={16916618,'Aern\'s Elemental',100},
    [147]={16916627,'Aern\'s Euvhi',109},
    [148]={16916628,'Aern\'s Elemental',100},
    [160]={16916640,'Aern\'s Wynav',193},
    [167]={16916647,'Aern\'s Euvhi',109},
    [257]={16916737,'Aern\'s Elemental',100},
    [266]={16916746,'Aern\'s Wynav',193},
    [282]={16916762,'Aern\'s Wynav',193},
    [283]={16916763,'Aern\'s Wynav',193},
    [315]={16916795,'Aern\'s Elemental',100},
    [316]={16916796,'Aern\'s Elemental',100},
    [326]={16916806,'Aern\'s Wynav',193},
    [332]={16916812,'Aern\'s Euvhi',109},
  },
}
