-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=35,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [21]={16920597,'Aern\'s Wynav',193},
    [31]={16920607,'Aern\'s Euvhi',109},
    [34]={16920610,'Aern\'s Elemental',100},
    [73]={16920649,'Aern\'s Elemental',100},
    [82]={16920658,'Aern\'s Euvhi',109},
    [87]={16920663,'Aern\'s Wynav',193},
    [204]={16920780,'Aern\'s Euvhi',109},
    [208]={16920784,'Aern\'s Wynav',193},
    [212]={16920788,'Aern\'s Elemental',100},
  },
}
