-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=39,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [239]={16937199,'Vanguard\'s Hecteyes',139},
    [243]={16937203,'Vanguard\'s Wyvern',193},
    [247]={16937207,'Vanguard\'s Avatar',34},
    [260]={16937220,'Vanguard\'s Scorpion',217},
    [266]={16937226,'Vanguard\'s Wyvern',193},
    [272]={16937232,'Vanguard\'s Avatar',34},
    [283]={16937243,'Vanguard\'s Wyvern',193},
    [287]={16937247,'Vanguard\'s Avatar',34},
    [297]={16937257,'Vanguard\'s Crow',55},
    [307]={16937267,'Vanguard\'s Wyvern',193},
    [309]={16937269,'Vanguard\'s Avatar',34},
    [322]={16937282,'Vanguard\'s Slime',229},
    [330]={16937290,'Arch Christelle',186},
    [351]={16937311,'Lost Nant\'ina',136},
    [455]={16937415,'Lost Stcemqestcint',245},
    [472]={16937432,'Lost Fairy Ring',116},
    [521]={16937481,'Vanguard\'s Avatar',34},
    [527]={16937487,'Vanguard\'s Hecteyes',139},
    [533]={16937493,'Vanguard\'s Wyvern',193},
    [547]={16937507,'Vanguard\'s Scorpion',217},
    [551]={16937511,'Vanguard\'s Wyvern',193},
    [558]={16937518,'Vanguard\'s Avatar',34},
    [570]={16937530,'Vanguard\'s Avatar',34},
    [578]={16937538,'Vanguard\'s Wyvern',193},
    [583]={16937543,'Vanguard\'s Crow',55},
    [596]={16937556,'Vanguard\'s Avatar',34},
    [602]={16937562,'Vanguard\'s Slime',229},
    [608]={16937568,'Vanguard\'s Wyvern',193},
  },
}
