-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=42,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [5]={16949253,'Diabolos\'s Shard',35},
    [6]={16949254,'Diabolos\'s Shard',35},
    [40]={16949288,'Hydra\'s Hound',143},
    [49]={16949297,'Hydra\'s Wyvern',193},
    [54]={16949302,'Hydra\'s Avatar',34},
    [78]={16949326,'Diabolos Somnus',35},
    [79]={16949327,'Diabolos Nox',35},
    [80]={16949328,'Diabolos Letum',35},
    [81]={16949329,'Diabolos Umbra',35},
    [82]={16949330,'Diabolos\'s Vestige',35},
    [83]={16949331,'Diabolos\'s Vestige',35},
    [104]={16949352,'Kindred\'s Vouivre',267},
    [120]={16949368,'Kindred\'s Avatar',34},
    [127]={16949375,'Kindred\'s Wyvern',193},
  },
}
