-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=46,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={16965633,'Passage Crab',77},
    [2]={16965634,'Passage Crab',77},
    [3]={16965635,'Gugru Jagil',197},
    [4]={16965636,'Gugru Jagil',197},
    [5]={16965637,'Blanched Kraken',218},
    [8]={16965640,'Gugru Crab',77},
    [9]={16965641,'Gugru Crab',77},
    [10]={16965642,'Ocean Jagil',197},
    [11]={16965643,'Ocean Jagil',197},
    [12]={16965644,'Ocean Kraken',218},
    [13]={16965645,'Revenant',121},
    [14]={16965646,'Thunder Elemental',105},
    [15]={16965647,'Water Elemental',106},
  },
}
