-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=47,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={16969729,'Passage Crab',77},
    [2]={16969730,'Passage Crab',77},
    [3]={16969731,'Gugru Jagil',197},
    [4]={16969732,'Gugru Jagil',197},
    [5]={16969733,'Blanched Kraken',218},
    [8]={16969736,'Gugru Crab',77},
    [9]={16969737,'Gugru Crab',77},
    [10]={16969738,'Ocean Jagil',197},
    [11]={16969739,'Ocean Jagil',197},
    [12]={16969740,'Ocean Kraken',218},
    [13]={16969741,'Revenant',121},
    [14]={16969742,'Thunder Elemental',105},
    [15]={16969743,'Water Elemental',106},
  },
}
