-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=57,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17010689,'Wootzshell',77},
    [2]={17010690,'Arrapago Leech',172},
    [3]={17010691,'Talacca Clot',66},
    [4]={17010692,'Lahama',218},
    [5]={17010693,'Llamhigyn Y Dwr',86},
    [31]={17010719,'Valkeng',28},
    [32]={17010720,'Valkeng',28},
    [33]={17010721,'Valkeng',28},
  },
}
