-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=58,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17014785,'Cyan Deep Crab',77},
    [2]={17014786,'Submarine Nipper',77},
    [3]={17014787,'Thalassic Pugil',197},
    [4]={17014788,'Abyssal Pugil',197},
    [5]={17014789,'Bathybic Kulshedra',218},
    [7]={17014791,'Apkallu',27},
    [8]={17014792,'Apkallu',27},
    [9]={17014793,'Bigclaw',77},
    [10]={17014794,'Bigclaw',77},
    [11]={17014795,'Cyan Deep Pugil',197},
    [12]={17014796,'Kulshedra',218},
    [13]={17014797,'Utukku',121},
    [15]={17014799,'Air Elemental',99},
    [16]={17014800,'Thunder Elemental',105},
  },
}
