-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=59,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [1]={17018881,'Cyan Deep Crab',77},
    [2]={17018882,'Submarine Nipper',77},
    [3]={17018883,'Thalassic Pugil',197},
    [4]={17018884,'Abyssal Pugil',197},
    [5]={17018885,'Bathybic Kulshedra',218},
    [7]={17018887,'Apkallu',27},
    [8]={17018888,'Apkallu',27},
    [9]={17018889,'Bigclaw',77},
    [10]={17018890,'Bigclaw',77},
    [11]={17018891,'Cyan Deep Pugil',197},
    [12]={17018892,'Kulshedra',218},
    [13]={17018893,'Utukku',121},
    [15]={17018895,'Air Elemental',99},
    [16]={17018896,'Thunder Elemental',105},
  },
}
