-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=63,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [40]={17035304,'Crimson Eruca',107},
    [41]={17035305,'Crimson Eruca',107},
    [42]={17035306,'Crimson Eruca',107},
    [43]={17035307,'Crimson Eruca',107},
    [44]={17035308,'Crimson Eruca',107},
    [45]={17035309,'Crimson Eruca',107},
    [206]={17035470,'Black Shuck',62},
  },
}
