-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=71,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [25]={17068057,'Pit Monster',0},
    [61]={17068093,'Pit Monster',0},
    [130]={17068162,'Pit Monster',0},
    [169]={17068201,'Pit Monster',0},
    [214]={17068246,'Pit Monster',0},
    [259]={17068291,'Pit Monster',0},
    [313]={17068345,'Pit Monster',0},
    [394]={17068426,'Pit Monster',0},
  },
}
