-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=72,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [2]={17072130,'Qiqirn Poulterer',199},
    [6]={17072134,'Qiqirn Poulterer',199},
    [7]={17072135,'Qiqirn Poulterer',199},
    [18]={17072146,'Qiqirn Poulterer',199},
    [19]={17072147,'Qiqirn Poulterer',199},
    [23]={17072151,'Qiqirn Poulterer',199},
    [30]={17072158,'Qiqirn Poulterer',199},
    [37]={17072165,'Qiqirn Poulterer',199},
    [38]={17072166,'Qiqirn Poulterer',199},
    [39]={17072167,'Qiqirn Poulterer',199},
    [45]={17072173,'Qiqirn Mine',236},
    [46]={17072174,'Qiqirn Mine',236},
    [47]={17072175,'Qiqirn Mine',236},
    [48]={17072176,'Qiqirn Mine',236},
    [49]={17072177,'Qiqirn Mine',236},
    [52]={17072180,'Vidmapire',284},
    [53]={17072181,'Vidmapire',284},
    [54]={17072182,'Vidmapire',284},
  },
}
