-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=73,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [110]={17076334,'Mamool Ja\'s Wyvern',193},
    [118]={17076342,'Mamool Ja\'s Wyvern',193},
    [120]={17076344,'Mamool Ja\'s Wyvern',193},
    [122]={17076346,'Mamool Ja\'s Wyvern',193},
    [124]={17076348,'Mamool Ja\'s Wyvern',193},
    [129]={17076353,'Mamool Ja\'s Lizard',174},
    [130]={17076354,'Mamool Ja\'s Lizard',174},
    [131]={17076355,'Mamool Ja\'s Lizard',174},
    [132]={17076356,'Mamool Ja\'s Lizard',174},
    [137]={17076361,'Mamool Ja\'s Wyvern',193},
    [138]={17076362,'Mamool Ja\'s Lizard',174},
    [143]={17076367,'Mamool Ja\'s Wyvern',193},
    [144]={17076368,'Mamool Ja\'s Lizard',174},
    [149]={17076373,'Mamool Ja\'s Wyvern',193},
    [150]={17076374,'Mamool Ja\'s Lizard',174},
    [152]={17076376,'Wajaom Tiger',242},
    [186]={17076410,'Wajaom Tiger',242},
    [192]={17076416,'Mamool Ja\'s Wyvern',193},
    [193]={17076417,'Mamool Ja\'s Lizard',174},
    [275]={17076499,'Slime Mold',229},
    [276]={17076500,'Slime Mold',229},
    [277]={17076501,'Slime Mold',229},
    [292]={17076516,'Wajaom Tiger',242},
    [308]={17076532,'Mindgazer',139},
    [309]={17076533,'Mindgazer',139},
    [310]={17076534,'Mindgazer',139},
    [333]={17076557,'Torama',71},
  },
}
