-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=75,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [109]={17084525,'Troll\'s Automaton',28},
    [111]={17084527,'Troll\'s Automaton',28},
    [121]={17084537,'Troll\'s Automaton',28},
    [124]={17084540,'Troll\'s Automaton',28},
    [126]={17084542,'Troll\'s Automaton',28},
    [140]={17084556,'Troll\'s Automaton',28},
    [158]={17084574,'Troll\'s Automaton',28},
    [160]={17084576,'Troll\'s Automaton',28},
    [162]={17084578,'Troll\'s Automaton',28},
    [168]={17084584,'Troll\'s Automaton',28},
    [173]={17084589,'Troll\'s Automaton',28},
    [180]={17084596,'Troll\'s Automaton',28},
    [185]={17084601,'Troll\'s Automaton',28},
    [282]={17084698,'Gate Widow',235},
    [289]={17084705,'Skirmish Pephredo',48},
    [296]={17084712,'Zebra Zachary',70},
    [303]={17084719,'Peryton',125},
    [305]={17084721,'Demented Jalaawa',233},
  },
}
