-- SPDX-License-Identifier: GPL-3.0-or-later
-- Generated by tools/build_weakness_data.py; do not edit.
-- CatsEye source commit: 4cf9796860e4a1fd338df15ee9b45406678400b9
-- Material input identity: sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5
return {
  schema=1,
  zone=8,
  sourceSha256='sha256:4cd25d99352991936abf2af8892f3f5685bfca669a10ba0adb97951d846f90d5',
  records={
    [68]={16810052,'Cadaver Warrior',227},
    [69]={16810053,'Cadaver Warrior',227},
    [70]={16810054,'Cadaver Warrior',227},
    [71]={16810055,'Cadaver Witch',227},
    [72]={16810056,'Cadaver Witch',227},
    [73]={16810057,'Cadaver Witch',227},
    [74]={16810058,'Erdgeist',121},
    [75]={16810059,'Erdgeist',121},
    [76]={16810060,'Erdgeist',121},
    [79]={16810063,'Cadaver Warrior',227},
    [80]={16810064,'Cadaver Warrior',227},
    [81]={16810065,'Cadaver Warrior',227},
    [82]={16810066,'Cadaver Witch',227},
    [83]={16810067,'Cadaver Witch',227},
    [84]={16810068,'Cadaver Witch',227},
    [85]={16810069,'Erdgeist',121},
    [86]={16810070,'Erdgeist',121},
    [87]={16810071,'Erdgeist',121},
    [90]={16810074,'Cadaver Warrior',227},
    [91]={16810075,'Cadaver Warrior',227},
    [92]={16810076,'Cadaver Warrior',227},
    [93]={16810077,'Cadaver Witch',227},
    [94]={16810078,'Cadaver Witch',227},
    [95]={16810079,'Cadaver Witch',227},
    [96]={16810080,'Erdgeist',121},
    [97]={16810081,'Erdgeist',121},
    [98]={16810082,'Erdgeist',121},
  },
}
